name: register-workspace

on: 
  workflow_call:
    inputs:
      resource_group:
        required: true
        type: string
      workspace_name:
        required: true
        type: string
#       location:
#         required: true
#         type: string
    secrets:
      creds:
        required: true
jobs:
  register-workspace:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          creds: ${{secrets.creds}}
          enable-AzPSSession: true 
      - name: install-extension
        run:  az extension add -n ml -y
      - name: update-extension
        run: az extension update -n ml
      - name: list-extentions
        run: az extension list
      - name: create-rg
        run: |
          az group create -n ${{ inputs.resource_group }} -l eastus
      - name: create-ws
        run: |
          az ml workspace create -n ${{ inputs.workspace_name }} -g ${{ inputs.resource_group }} -l eastus
